name: CodeCamp Approval Workflow
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Automate Approval
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
