name: Code Review

# Controls when the action will run. 
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: read-log-action
      uses: ./.github/actions/read-log-action
      id: read-log
      with:
        path-to-log-file: "tests/logfile.txt"

    - name: calculate-stats-action
      uses: ./.github/actions/calculate-stats-action
      with:
        log-file-content: ${{ steps.read-log.outputs.log-file-content }}
